name: deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js v14.x
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: Install
        run: npm install

      - name: Build
        run: npm run build
        env:
          VITE_MORALIS_APP_ID: ${{ secrets.VITE_MORALIS_APP_ID }}
          VITE_MORALIS_SERVER_URI: ${{ secrets.VITE_MORALIS_SERVER_URI }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        env:
          VITE_MORALIS_APP_ID: ${{ secrets.VITE_MORALIS_APP_ID }}
          VITE_MORALIS_SERVER_URI: ${{ secrets.VITE_MORALIS_SERVER_URI }}
        with:
          publish_dir: ./dist
          commit_message: Update Vite2.x + Vue3.x + TypeScript Starter